version: 0.2

phases:
  
  pre_build:
    commands:
      apt update
      apt install -y docker.io

  build:
    commands:
      docker build -t oneequine/iea-apigateway-image -f ./apps/iea-apigateway/Dockerfile .
      docker build -t oneequine/logger-image -f ./apps/logger/Dockerfile .
      docker build -t oneequine/notification-image -f ./apps/notification/Dockerfile .

  post_build:
    commands:
      # Tag Push images to Docker Hub
      docker tag oneequine/iea-apigateway-image:latest 045113578396.dkr.ecr.us-east-1.amazonaws.com/oneequine/iea-apigateway-image:latest
      docker push 045113578396.dkr.ecr.us-east-1.amazonaws.com/oneequine/iea-apigateway-image:latest
      docker tag oneequine/logger-image:latest 045113578396.dkr.ecr.us-east-1.amazonaws.com/oneequine/logger-image:latest
      docker push 045113578396.dkr.ecr.us-east-1.amazonaws.com/oneequine/logger-image:latest
      docker tag oneequine/notification-image:latest 045113578396.dkr.ecr.us-east-1.amazonaws.com/oneequine/notification-image:latest
      docker push 045113578396.dkr.ecr.us-east-1.amazonaws.com/oneequine/notification-image:latest
