version: 0.2

phases:
  
  pre_build:
    commands:
      - ACCOUNT_URI=045113578396.dkr.ecr.us-east-1.amazonaws.com
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ACCOUNT_URI

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - |
        for app_dir in apps/iea-apigateway apps/logger apps/notification; do
          image_name=$(basename $app_dir)
          echo Building $image_name Docker image...
          docker build -t oneequine/$image_name-image -f ./$app_dir/Dockerfile .
        done

  post_build:
    commands:
      - echo Build completed on `date`
      - |
        for image_name in iea-apigateway-image logger-image notification-image; do
          echo Pushing $image_name Docker image to ECR...
          docker tag oneequine/$image_name:latest $ACCOUNT_URI/oneequine/$image_name:latest
          docker push $ACCOUNT_URI/oneequine/$image_name:latest
          printf '[{"name":$image_name,"imageUri":"%s"}]' $ACCOUNT_URI/oneequine/$image_name:latest > imagedefinitions_${image_name}.json
        done

artifacts:
    files: 
       - imagedefinitions_iea-apigateway-image.json
       - imagedefinitions_logger-image.json
       - imagedefinitions_notification-image.json

